# run khuong and postgres

services:
  khuong:
    image: khuong
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  postgres-memory-chatbot:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=matkhau
      - POSTGRES_USER=postgres
      - POSTGRES_DB=memory-chatbot
    volumes:
      - ./postgres:/var/lib/postgresql/data